# Generated by Django 4.0 on 2023-04-23 19:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Headquarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter field documentation', max_length=60)),
                ('status', models.CharField(blank=True, choices=[('o', 'Open'), ('n', 'No data.'), ('c', 'Closed')], default='n', max_length=1)),
                ('country', models.CharField(help_text='Enter field documentation', max_length=60)),
                ('address', models.CharField(help_text='Enter field documentation', max_length=120)),
                ('phone', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('email', models.CharField(help_text='Enter field documentation', max_length=40)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Enter field documentation')),
                ('years_on_market', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(max_length=20)),
                ('headquarter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.headquarter')),
            ],
            options={
                'ordering': ['name', 'years_on_market'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter field documentation', max_length=60)),
                ('description', models.TextField(help_text='Enter field documentation')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter field documentation', max_digits=10)),
                ('image', models.ImageField(help_text='Enter field documentation', null=True, upload_to='')),
                ('furniture_type', models.ManyToManyField(to='mainapp.FurnitureType')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.manufacturer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter field documentation', max_length=60)),
                ('phone', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('email', models.CharField(help_text='Enter field documentation', max_length=40)),
                ('address', models.CharField(help_text='Enter field documentation', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('a', 'Available'), ('m', 'Maintenance'), ('r', 'Reserved')], default='m', max_length=1)),
                ('buyer', models.CharField(help_text='Enter field documentation', max_length=120)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.product')),
            ],
        ),
    ]
